# .air.toml for API
root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./bin/api ./cmd/api"
bin = "bin/api"
full_bin = "./bin/api"
exclude_dir = ["bin", "tmp", "vendor", "cmd/cli"]

[log]
time = true
